### ISSUE TITLE
Pod sidecar "Show logs" button will fail if pod has multiple containers

### ISSUE THREAD

**Issue by showeimer** [kui-shell/plugin-kubeui#275]
The executed `kubectl logs` command will fail and ask the user to provide the desired container name inside the pod.

**Comment by starpit** [comment]
isn't this an issue with the underlying kubectl? i.e. we could improve on this behavior, but it isn't a bug in kui?

**Comment by showeimer** [comment]
@starpit I don't think this is an issue with the underlying kubectl; kubectl requires the user to provide the container name if multiple containers live in the same pod.  kubectl will return an error like this to guide the user:

`
Error from server (BadRequest): a container name must be specified for pod auth-idp-th82t, choose one of: [icp-audit-service platform-auth-service platform-identity-provider platform-identity-manager]
`

**Comment by starpit** [comment]
i'm seeing the same error when i click on a multi-container pod?

**Comment by showeimer** [comment]
@starpit What I'm trying to point out is that the `Show logs` button does not support/is broken in this common situation.  Kubectl does not aggregate all the container logging when you run a `kubectl logs` command; nor would that make sense to do so.  There should be some behavior in this situation, where a table is presented with the containers to choose from or something:

1 container

- Click `Show logs`
- KUI does not receive this error message, and proceeds to show the logs

2+ containers

- Click `Show logs`
- KUI catches this error and displays an interaction that allows the user to choose the desired container and runs a new `kubectl logs pod-abc` command with the `-c <container name>` appended.

**Comment by hanqiuzh** [comment]
I think the problem here is whether we should show the `Show Logs` button if the pod has multiple containers? 

Many pods will have more than one container (for sidecar/proxy/...), and current design (show error) is confusing.

Or we can always choose one container as default?

**Comment by starpit** [comment]
nice thoughts, thanks for the insights! it seems like we have three options, as proposed:

1) detect multi-container pods, and don't show the Show Logs button (for now, at least)
2) same, but instead present a container table
3) combine the logs for the user, into a single response (with some prefix discriminant for the log entries)

#1 will be very easy, and you can do this in a pretty simple PR against this line: https://github.com/kui-shell/plugin-kubeui/blob/v1.0.8/plugins/plugin-logui/src/modes/show-logs.ts#L51

#2 would require a new command, but wouldn't require very much new code at all

#3 wouldn't require a new command, but instead changing the behavior of the current `k logs` handler

**Comment by mark-nc** [comment]
#3 would be very counterintuitive to users who are used to using the `kubectl logs` command.   No other command (or UI that has been used in existing cloud products) has combined logs from multiple containers in a pod into a single log output.

#1 is a stopgap until a better solution could be designed.

#2 seems like it might work if in the multi-container case it gave you a list of containers and then you could click one to see the log for that one container, with a way to navigate back.

**Comment by starpit** [comment]
`kubectl logs --all-containers` is a thing, so i think option 3 is viable?

**Comment by mark-nc** [comment]
OK, yes.  But then there are other combinations, for example,

`kubectl logs -l app=nginx` will list logs from all containers matching the app label specified.

I think the key here is if we take a user command and then transform it into a slightly different command rather than what he or she asked for, then we will get bug reports for that.  Maybe the better stop gap measure would be if there is more than one container in the pod and we get the error, I like Sho's approach where we issue a command to list the containers so the user can then know what new command to issue for the specific container of interest.  Someone checking logs is usually interested in a specific container, but may not know immediately there are multiple containers or what the containers are called.

**Comment by starpit** [comment]
this is re: a button in a Pod sidecar, i.e. the user already selected a particular pod-by-name, not a pod-by-query (e.g. by label)?

**Comment by starpit** [comment]
and we already have the Containers tab that lets users drill down to specific containers (of their choosing), so we probably don't need to invent another UI for that. if anything, we should focus *that* effort on refining the presentation of the Containers tab? e.g. we aren't including anything about resource consumption or quotas, but we could! and we could make the transition to logs (from the Containers) tab more explicit -- right now, it's hidden under an onclick attached to the container name.

**Comment by starpit** [comment]
it looks like show-logs.ts already is doing a `--all-containers` for deployments: 
https://github.com/kui-shell/plugin-kubeui/blob/v1.0.8/plugins/plugin-logui/src/modes/show-logs.ts#L27

i propose that we add the same option to the pod handler:
https://github.com/kui-shell/plugin-kubeui/blob/v1.0.8/plugins/plugin-logui/src/modes/show-logs.ts#L43

**Comment by starpit** [comment]
https://github.com/kui-shell/plugin-kubeui/pull/324/files

**Comment by mark-nc** [comment]
OK....this is probably a better option for now than just getting an error back, but we should probably revisit these cases with design to see if there are other UX patterns that would be even better.

**Comment by starpit** [comment]
should be resolved with #325
