### ISSUE TITLE
Strange sidecar behavior when using log features

### ISSUE THREAD

**Issue by showeimer** [kui-shell/plugin-kubeui#290]
#### 1.  `kubectl get pods`, and click a pod -- sidecar opens.

<img width="511" alt="Screen Shot 2020-01-27 at 12 06 48 PM" src="https://user-images.githubusercontent.com/26075187/73196487-a6f1f600-40fd-11ea-8e75-bc54b208ca75.png">

#### 3.  The "Containers` tab content will become blank:

<img width="472" alt="Screen Shot 2020-01-27 at 12 07 19 PM" src="https://user-images.githubusercontent.com/26075187/73196508-b1ac8b00-40fd-11ea-88bf-c178aa62088a.png">

#### 4.  Click the back arrow button in the sidecar, an input field appears below the title

<img width="489" alt="Screen Shot 2020-01-27 at 12 07 36 PM" src="https://user-images.githubusercontent.com/26075187/73196572-d43ea400-40fd-11ea-85d4-c4e50364fc14.png">

**Comment by starpit** [comment]
nice catch, thanks. on it

**Comment by starpit** [comment]
this is actually a bug in the core https://github.com/IBM/kui/issues/3571 moving the issue there
