### ISSUE TITLE
Usability issues with logging feature

### ISSUE THREAD

**Issue by showeimer** [kui-shell/plugin-kubeui#291]
The logging feature in KUI has some usability issues; here are a few problems I've noticed:

1.  [ ] Logs seem to be capped at 20 or less lines.
2.  [ ] Logs are presented in a table format, as opposed to a more conventional logging format.
3.  [x] If `-f` is used, the browser will freeze up because an extraordinary amount of HTML is being generated (a `span` for each letter).
4.  [ ] Long log lines will get truncated at the table border, user cannot scroll to see the rest; nor should they have to? 
5.  [ ] No search feature in logs.

It would be great to get a UX designer's input to improve this feature.

**Comment by starpit** [comment]
i will cover the third issue in #304
