### ISSUE TITLE
tag kubeResource to help distinguish kubeResource from open-ended structure response 

### ISSUE THREAD

**Issue by myan9** [kui-shell/plugin-kubeui#339]
A structure response is associated with `apiVersion` and `kind`. For now, there's no good way for `isKubeResource` to distinguish `kubeResource` from the open-ended structure responses. Therefore, sometimes we will see the `Summary` tab open for non-kube resource that contains apiVersion and kind.

**Comment by starpit** [comment]
closed by #340; was not auto-closed, due to a typo in the issue comment (missing hash)
