### ISSUE TITLE
oc describe commands fail with error due to -o parameter

### ISSUE THREAD

**Issue by mark-nc** [kui-shell/plugin-kubeui#445]
Using plugin-kubeui v1.0.14 with kui-shell/core v6.0.17 `oc describe` commands fail due to the addition of the `-o yaml` parameter.  That parameter works with `kubectl describe` but is not supported with `oc describe`.

To reproduce:

`oc describe pod -n open-cluster-management application-chart-ad4ea-applicationui-7c6b69fdd7-mgs2b`
Error: unknown shorthand flag: 'o' in -o
See 'oc describe --help' for usage.

`oc describe --help`
Error: unknown shorthand flag: 'o' in -o
See 'oc describe --help' for usage.

`oc describe`
Error: unknown shorthand flag: 'o' in -o
See 'oc describe --help' for usage.

There may be other `oc` commands where the supported flags are not 100% in line with the same `kubectl` commands.  For users of Red Hat OpenShift, this is a significant bug.

**Comment by hanqiuzh** [comment]
verified issue still exists in 1.0.15
typed `oc describe --help` ,returned combined results of `kubectl` and `oc get`, nothing related to `oc describe` 
<img width="1040" alt="Screen Shot 2020-03-24 at 4 37 03 PM" src="https://user-images.githubusercontent.com/31426239/77474949-61486580-6dee-11ea-85d9-32c4274e6e66.png">

**Comment by starpit** [comment]
released in 1.0.16
